"""ad_rewards tablosu oluşturuldu

Revision ID: 061d9f27d03d
Revises: 44bc4f714cd9
Create Date: 2025-12-13 14:13:14.657979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061d9f27d03d'
down_revision: Union[str, Sequence[str], None] = '44bc4f714cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Otomatik artan ID'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Kullanıcı ID (users.user_id referansı)'),
    sa.Column('rewards_type', sa.String(length=100), nullable=False, comment='Ödül tipi (diamond, coin, hint, xp, vb.)'),
    sa.Column('rewards_values', sa.Integer(), nullable=False, comment='Ödül miktarı'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Ödül kazanılma tarihi'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_rewards_id'), 'ad_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_ad_rewards_user_id'), 'ad_rewards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_rewards_user_id'), table_name='ad_rewards')
    op.drop_index(op.f('ix_ad_rewards_id'), table_name='ad_rewards')
    op.drop_table('ad_rewards')
    # ### end Alembic commands ###
