"""Rating Tablosu Oluşturuldu

Revision ID: 2dbc14f0cad4
Revises: 604e04dd74bc
Create Date: 2025-12-13 13:58:57.530469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbc14f0cad4'
down_revision: Union[str, Sequence[str], None] = '604e04dd74bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Otomatik artan ID'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Kullanıcı ID (users.user_id referansı)'),
    sa.Column('level_id', sa.Integer(), nullable=False, comment='Seviye ID (levels.id referansı)'),
    sa.Column('stars', sa.Integer(), nullable=False, comment='Yıldız sayısı: 1, 2 veya 3'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Oluşturulma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Güncellenme tarihi'),
    sa.CheckConstraint('stars >= 1 AND stars <= 3', name='check_stars_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_index(op.f('ix_rating_level_id'), 'rating', ['level_id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_level_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
