"""Level tablosu oluşturuldu

Revision ID: 44bc4f714cd9
Revises: 2dbc14f0cad4
Create Date: 2025-12-13 14:08:20.095117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bc4f714cd9'
down_revision: Union[str, Sequence[str], None] = '2dbc14f0cad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Otomatik artan ID'),
    sa.Column('level_id', sa.String(length=255), nullable=False, comment='Unique level ID (örn: lvl_001, lvl_002)'),
    sa.Column('level_no', sa.Integer(), nullable=False, comment='Seviye numarası'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='Zorluk seviyesi (1: Kolay, 2: Orta, 3: Zor, vb.)'),
    sa.Column('level_mode', sa.String(length=100), nullable=False, comment='Seviye modu (classic, time_trial, challenge, vb.)'),
    sa.Column('answer_value', sa.Integer(), nullable=False, comment='Doğru cevap değeri'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Seviye aktif mi? (True/False)'),
    sa.Column('hint1', sa.JSON(), nullable=True, comment='Birinci ipucu - Çoklu dil: {"tr": "İpucu", "en": "Hint", "de": "Hinweis"}'),
    sa.Column('hint2', sa.JSON(), nullable=True, comment='İkinci ipucu - Çoklu dil: {"tr": "İpucu", "en": "Hint", "de": "Hinweis"}'),
    sa.Column('solution_explanation', sa.JSON(), nullable=True, comment='Çözüm açıklaması - Çoklu dil: {"tr": "Açıklama", "en": "Explanation", "de": "Erklärung"}'),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='Seviye görseli yolu'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Oluşturulma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Güncellenme tarihi'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_level_id'), 'levels', ['level_id'], unique=True)
    op.create_index(op.f('ix_levels_level_no'), 'levels', ['level_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_levels_level_no'), table_name='levels')
    op.drop_index(op.f('ix_levels_level_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
