"""Users Tablosu ful şeması oluşturuldu

Revision ID: 604e04dd74bc
Revises: fb0ea9930729
Create Date: 2025-12-13 13:54:07.430032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '604e04dd74bc'
down_revision: Union[str, Sequence[str], None] = 'fb0ea9930729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=255), nullable=False, comment='Random unique user ID'))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False, comment="Hash'lenmiş şifre"))
    op.add_column('users', sa.Column('is_guest', sa.Integer(), nullable=False, comment='0: Normal kullanıcı, 1: Misafir'))
    op.add_column('users', sa.Column('locale', sa.String(length=10), nullable=True, comment='Dil kodu (tr, en, vb.)'))
    op.add_column('users', sa.Column('country', sa.String(length=5), nullable=True, comment='Ülke kodu (TR, US, vb.)'))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False, comment='Kullanıcının toplam XP seviyesi'))
    op.add_column('users', sa.Column('xp_dd', sa.Integer(), nullable=False, comment="XP kesir/detay - her 100'de xp +1"))
    op.add_column('users', sa.Column('diamond', sa.Integer(), nullable=False, comment='Elmas bakiyesi'))
    op.add_column('users', sa.Column('hints', sa.Integer(), nullable=False, comment='İpucu (hint) bakiyesi'))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False, comment='Kullanıcının ulaştığı seviye numarası'))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False, comment='Hesap durumu: active, banned, suspended'))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=500), nullable=True, comment='Kullanıcı profil fotoğrafı yolu'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Hesap oluşturulma tarihi'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Son güncellenme tarihi'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Son giriş tarihi'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete - silinme tarihi'))
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Otomatik artan ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='Kullanıcı adı',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='E-posta adresi',
               existing_nullable=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='E-posta adresi',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Kullanıcı adı',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Otomatik artan ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'status')
    op.drop_column('users', 'level')
    op.drop_column('users', 'hints')
    op.drop_column('users', 'diamond')
    op.drop_column('users', 'xp_dd')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'country')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'is_guest')
    op.drop_column('users', 'password')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
